image: node:6.3.1

before_script:
  - apt-get update -qq #&& apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
  - apt-get install -y zip
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.22.0
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  paths:
  - node_modules/

all_tests:
  script:
    - yarn install
    - yarn test
